### ISSUE TITLE
Possible outdated duplicate

### ISSUE THREAD

**Issue by NexiusTailer** [samp-anti-cheat/Anti_cheat_pack#1]
Is it an old duplicate of [that protection](https://github.com/RogueDrifter/Anti_cheat_pack)? I just don't see the big differences in this repo relative to the old versions of "RogueDrifter/Anti_cheat_pack". It might make sense to update this fork or archive it.

**Comment by RogueDrifter** [comment]
Yes my friend you're right, I'll archive it and leave a reference, this is outdated indeed
